version: "3"

services:
  app:
    build: .
    container_name: node-typescript-fastify
    network_mode: bridge
    volumes:
      - ./:/code
      - /code/node_modules
    ports:
      - 3000:3000